[package]
name = "neurons"
version = "0.1.0"
authors = ["Darren Tsung <darren@onesignal.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
rand_distr = "0.2.1"

[dev-dependencies]
approx = "0.3.2"
